version: '3.4'

volumes:
  dauthenticator_local_postgres_data: {}
  dauthenticator_local_postgres_data_backups: {}

services:
  django:
    &django
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_ENVIRONMENT: "local"
    image: dauthenticator_local_image
    container_name: dauthenticator_local_server
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8011:8000"
    command: start_server

  postgres:
    image: releases.registry.docker.kaisens.fr/kaisensdata/devops/docker-images/postgresql:14.5-1
    container_name: dauthenticator_local_postgres
    volumes:
      - dauthenticator_local_postgres_data:/var/lib/postgresql/data:Z
      - dauthenticator_local_postgres_data_backups:/backups:z
    env_file:
      - ./.env

  redis:
    image: redis:6
    container_name: adauthenticator_local_redis

  celeryworker:
    <<: *django
    image: dauthenticator_local_celeryworker
    container_name: dauthenticator_local_celeryworker
    depends_on:
      - redis
      - postgres
    restart: always
    env_file:
      - ./.env
    ports: []
    command: start_worker

  celerybeat:
    <<: *django
    image: dauthenticator_local_celerybeat
    container_name: dauthenticator_local_celerybeat
    depends_on:
      - redis
      - postgres
    restart: always
    ports: []
    env_file:
      - ./.env
    command: start_beat
